import { useModelEditor } from "@/hooks/useModelEditor";
import { servicemaxProjection } from "@/lib/pricing";
import { compactCurrency, currency, number } from "@/lib/format";
import type { ServiceMaxModel } from "@/types/deal";
import SectionCard from "@/components/common/SectionCard";
import KpiCard from "@/components/common/KpiCard";
import AssumptionField from "@/components/common/AssumptionField";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Wrench } from "lucide-react";

export default function ServiceMaxPage() {
  const { model, update, isLoading, canEdit, dirty, save, saving } = useModelEditor<ServiceMaxModel>("servicemax");
  if (isLoading || !model) return <p className="text-sm text-muted-foreground">Loading ServiceMax assumptions…</p>;

  const p = servicemaxProjection(model);

  return (
    <div className="space-y-6">
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard label="Incremental users" value={number(p.incremental)} icon={Wrench} />
        <KpiCard label="Net unit price" value={currency(p.netUnitPrice, "USD", 0)} hint={`${model.discount_pct}% discount applied`} />
        <KpiCard label="Annual ACV at full ramp" value={currency(p.annual)} tone="positive" />
        <KpiCard label="Ramp year" value={`Year ${model.ramp_year}`} hint={`Go-live ${model.go_live_date}`} />
      </div>

      <SectionCard title="ACV ramp" description="Recognised Service Cloud value by contract year">
        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={p.years} margin={{ left: 8, right: 8 }}>
              <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="hsl(var(--border))" />
              <XAxis dataKey="year" tick={{ fontSize: 11 }} stroke="hsl(var(--muted-foreground))" />
              <YAxis tickFormatter={(v) => compactCurrency(Number(v))} tick={{ fontSize: 11 }} stroke="hsl(var(--muted-foreground))" />
              <Tooltip formatter={(v) => currency(Number(v))} contentStyle={{ background: "hsl(var(--card))", border: "1px solid hsl(var(--border))", borderRadius: 8 }} />
              <Bar dataKey="acv" name="ACV" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </SectionCard>

      <SectionCard
        title="Field service population"
        description="Licence demand generated by the ServiceMax programme"
        actions={<Button size="sm" disabled={!canEdit || !dirty || saving} onClick={save}>Save</Button>}
      >
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          <AssumptionField label="Current service baseline" value={model.current_service_baseline} onChange={(v) => update({ current_service_baseline: v })} disabled={!canEdit} />
          <AssumptionField label="Project population" value={model.project_population} onChange={(v) => update({ project_population: v })} disabled={!canEdit} />
          <AssumptionField label="Full service users" value={model.full_service_users} onChange={(v) => update({ full_service_users: v })} disabled={!canEdit} />
          <AssumptionField label="Dispatcher users" value={model.dispatcher_users} onChange={(v) => update({ dispatcher_users: v })} disabled={!canEdit} />
          <AssumptionField label="Internal support users" value={model.internal_support_users} onChange={(v) => update({ internal_support_users: v })} disabled={!canEdit} />
          <AssumptionField label="Partner users" value={model.partner_users} onChange={(v) => update({ partner_users: v })} disabled={!canEdit} hint="Community licensing to confirm" />
          <AssumptionField label="Integration users" value={model.integration_users} onChange={(v) => update({ integration_users: v })} disabled={!canEdit} />
          <AssumptionField label="Required sandboxes" value={model.required_sandboxes} onChange={(v) => update({ required_sandboxes: v })} disabled={!canEdit} />
          <AssumptionField label="Unit price" value={model.unit_price} step={50} onChange={(v) => update({ unit_price: v })} disabled={!canEdit} />
          <AssumptionField label="Discount" suffix="%" value={model.discount_pct} onChange={(v) => update({ discount_pct: v })} disabled={!canEdit} />
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Go-live date</Label>
            <Input type="date" value={model.go_live_date} disabled={!canEdit} onChange={(e) => update({ go_live_date: e.target.value })} />
          </div>
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Ramp year</Label>
            <Select value={String(model.ramp_year)} disabled={!canEdit} onValueChange={(v) => update({ ramp_year: Number(v) as ServiceMaxModel["ramp_year"] })}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="1">Year 1</SelectItem>
                <SelectItem value="2">Year 2</SelectItem>
                <SelectItem value="3">Year 3</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="mt-4 grid gap-4 md:grid-cols-2">
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Required add-ons</Label>
            <Input value={model.required_addons} disabled={!canEdit} onChange={(e) => update({ required_addons: e.target.value })} />
          </div>
          <div className="space-y-1.5">
            <Label className="text-xs text-muted-foreground">Notes</Label>
            <Textarea value={model.notes} disabled={!canEdit} onChange={(e) => update({ notes: e.target.value })} />
          </div>
        </div>
      </SectionCard>
    </div>
  );
}
